### ISSUE TITLE
Plugin crashes when encountering tags with no attributes

### ISSUE THREAD

**Issue by chris-heijdens** [Joe-Withey/parcel-plugin-html-root-syntax#1]
The plugin currently assumes that all tag/attribute pairs that it searches for (script/src and link/href) actually have the attribute set. The plugin crashes when it encounters one that doesn't.

For example:
<script>
console.log("this inline script will crash the plugin");
</script>

**Comment by Joe-Withey** [comment]
Fixed by Chris in https://github.com/Joe-Withey/parcel-plugin-html-root-syntax/pull/2

Thanks Chris :)
